### DISCUSSION TITLE
[error] Protocol 'inet_tcp': register/listen error: eacces

### DISCUSSION THREAD

**Discussion by maxjf1** [docker-library/rabbitmq#472] [General]
I was using rabbitmq image normally for the past few months. today, i'm trying to use it and i'm having the following error:

```bash
Creating network "node-ocr-server_default" with the default driver
Creating node-ocr-server_rabbitmq_1 ... done
Attaching to node-ocr-server_rabbitmq_1
rabbitmq_1  | Distribution failed: {{:shutdown, {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}}, {:child, :undefined, :net_sup_dynamic, {:erl_distribution, :start_link, [[:"rabbitmqcli-47-rabbit@deb0e3b8af05", :shortnames, 15000], false]}, :permanent, 1000, :supervisor, [:erl_distribution]}}
rabbitmq_1  | Protocol 'inet_tcp': register/listen error: eacces
node-ocr-server_rabbitmq_1 exited with code 1
```

I am using docker compose with the following settings:

```yml
version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
```
Even without any ports it doesn't work. Older projects stopped working as well (without changes)

My system:

```bash
              ............                maxjf1@DELL-NOTE-MAX
          .';;;;;.       .,;,.            OS: Deepin 15.11 stable
       .,;;;;;;;.       ';;;;;;;.         Kernel: x86_64 Linux 4.15.0-30deepin-generic
     .;::::::::'     .,::;;,''''',.       Uptime: 1h 39m
    ,'.::::::::    .;;'.          ';      Packages: 2431
   ;'  'cccccc,   ,' :: '..        .:     Shell: zsh 5.3.1
  ,,    :ccccc.  ;: .c, '' :.       ,;    Resolution: 1920x1080
 .l.     cllll' ., .lc  :; .l'       l.   WM: KWin
 .c       :lllc  ;cl:  .l' .ll.      :'   GTK Theme: Mojave-dark [GTK2/3]
 .l        'looc. .   ,o:  'oo'      c,   Icon Theme: Mojave-CT-Night-Mode
 .o.         .:ool::coc'  .ooo'      o.   CPU: Intel Core i5-8300H CPU @ 4GHz
  ::            .....   .;dddo      ;c    GPU: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
   l:...            .';lddddo.     ,o     RAM: 4498MiB / 7836MiB
    lxxxxxdoolllodxxxxxxxxxc      :l     
     ,dxxxxxxxxxxxxxxxxxxl.     'o,      
       ,dkkkkkkkkkkkkko;.    .;o;        
         .;okkkkkdl;.    .,cl:.          
             .,:cccccccc:,.  

```

**Comment by wglambert** [comment]
Is anything else using that port?
You could also try asking one of the Rabbitmq resources https://github.com/rabbitmq/rabbitmq-server#getting-help or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=rabbitmq)

These issues look relevant to the error message
https://groups.google.com/forum/#!topic/rabbitmq-users/Pxp9GlVKfbU
https://stackoverflow.com/a/51629011

**Comment by maxjf1** [comment]
> Is anything else using that port?

No, as i said, even not exposing any ports i get this error

> These issues look relevant to the error message

I've tried them but they talk about missing connections and ports, but i'm using an docker container, that shouldn't make any difference...

**Comment by sajtrus** [comment]
I have a similar issue.

My docker-compose:
```
version: '3.7'
services:
  rabbitmq3:
    image: "rabbitmq:3-management"
    command: rabbitmq-server
    ports:
      - 4369:4369
      - 5672:5672
      - 15672:15672
      - 25672:25672
```
Then I do `sudo rabbitmqctl status`,
and I get this error:
```
Distribution failed: {{:shutdown, {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}}, {:child, :undefined, :net_sup_dynamic, {:erl_distribution, :start_link, [[:"rabbitmqcli-39293-rabbit@localhost", :shortnames, 15000], false, :net_sup_dynamic]}, :permanent, 1000, :supervisor, [:erl_distribution]}}
```

**Comment by maxjf1** [comment]
Something happened with my OS and every Container had network issues. So i've reinstalled linux, it was the only solution i've found...

**Comment by sajtrus** [comment]
@maxjf1 Crazy! 
I'm on macOS and I don't know what to do :( Is this your final docker-compose? 
```
version: '3.7'
services:
  rabbitmq3:
    image: "rabbitmq:3-management"
    command: rabbitmq-server
    ports:
      - 4369:4369
      - 5672:5672
      - 15672:15672
      - 25672:25672
```
Can you then do `sudo rabbitmqctl status` without any issues?
