### DISCUSSION TITLE
Docker container startup / shutdown

### DISCUSSION THREAD

**Discussion by plummyp** [docker-library/rabbitmq#563] [Q&A] [answered]
I have an issue with the start up of rabbitmq using image rabbitmq:3.10.2-alpine and docker compose.

When the container starts, there is a period of about 20 seconds where there are no logs or anything, then "list of feature flags found" log starts and it then takes another 70 seconds to get to "started TCP listener on [::]:5672"

So in total taking 90 seconds to startup. If I run rabbitmq outside of the container is takes about 10 seconds to startup.

I have also noticed that the normal SIGINT sent by docker stop does not work, but the logs do suggest that the app closes down gracefully when it receives SIGKILL - is this expected and should we always use kill instead of stop?

Many thanks

**Comment by lukebakken** [comment]
Please, _always_ provide the exact commands and files you're using so we won't have to guess how to reproduce your issue.

**Reply by plummyp** [reply]
OK, to bring up the container, this is the docker compose file:

```
services:

  rabbitmq:
    image: rabbitmq:3.10.2-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    network_mode: "host"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: some_user
      RABBITMQ_DEFAULT_PASS: some_pass
```
I then run docker compose up -d

To run outside of the container, I did apt install rabbitmq-server and then sytemctl start rabbitmq-server.service

After re-checking its actually only taking about 3s to start up outside of the container. Im just doing netstat to watch when the port 5672 becomes available for timing.

The host is running Ubuntu 20.04

docker -v
Docker version 20.10.17, build 100c701

Using compose plugin:
docker compose version
Docker Compose version v2.6.0

**Reply by plummyp** [reply]
As a test I used image: rabbitmq:3.10 rather than rabbitmq:3.10.2-alpine and it improved dramatically.

It's now starting up ready for connections in under 5 seconds. It is now also accepting the SIGINT on stop.

**Reply by lukebakken** [reply]
Thank you for all of this information. I am testing using the following host:

```
$ cat /etc/lsb-release
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"

$ uname -a
Linux shostakovich 5.15.46-1-lts #1 SMP Thu, 09 Jun 2022 10:12:44 +0000 x86_64 GNU/Linux

$ docker -v
Docker version 20.10.17, build 100c70180f

$ docker compose version
Docker Compose version 2.6.0
```

This command starts RabbitMQ in under 5 seconds:
```
docker run --rm --publish 5672:5672 rabbitmq:3.10.5-alpine
```

Running `docker stop` on that container works as expected:
```
2022-06-14 13:23:44.149383+00:00 [notice] <0.60.0> SIGTERM received - shutting down
2022-06-14 13:23:44.149383+00:00 [notice] <0.60.0>
2022-06-14 13:23:44.150700+00:00 [warning] <0.699.0> HTTP listener registry could not find context rabbitmq_prometheus_tls
2022-06-14 13:23:44.155905+00:00 [info] <0.221.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping unregistration.
2022-06-14 13:23:44.155978+00:00 [info] <0.747.0> stopped TCP listener on [::]:5672
```

`docker-compose.yml` file that I use next. NOTE: I am using `bridge` mode because that is the default mode that `docker run` uses:
```yaml
services:
  rabbitmq:
    image: rabbitmq:3.10.5-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    network_mode: bridge
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: some_user
      RABBITMQ_DEFAULT_PASS: some_pass
```

Using the above configuration, `docker compose up` runs as fast as `docker run`. Stopping the container with `docker compose stop` works as expected.


However, if I switch to `network_mode: host`, startup is indeed slower. The "Attaching to rabbitmq" phase takes longer, and the RabbitMQ startup takes 30 seconds.

`docker compose stop` works as expected.

I'm not sure why `host` mode takes longer for startup, but once started, the RabbitMQ container works as expected.

Switching to the `rabbitmq:3-management` container, which is based on Ubuntu, behaves in the same manner as the one based on Alpine.

This issue appears to be limited to `docker compose`, because the following command runs quickly:

```
docker run --network=host --rm rabbitmq:3-management-alpine
```

**Comment by lukebakken** [comment, marked as answer]
@plummyp my colleague @essen figured it out pretty quickly. When you use `host` networking mode, the containers will be using your host's DNS resolution service. If the `rabbitmq` hostname does NOT resolve in DNS, you will experience this slow startup.

I fixed the issue in my test environment by adding the following line to `/etc/hosts` in the host OS:

```
127.0.0.1        rabbitmq
```

**Reply by plummyp** [reply]
Thanks for the response. After adding extra_hosts to the compose file:

```
services:

  rabbitmq:
    image: rabbitmq:3.10.2-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    network_mode: "host"
    restart: always
    extra_hosts:
      - "rabbitmq:127.0.0.1"
    environment:
      RABBITMQ_DEFAULT_USER:
      RABBITMQ_DEFAULT_PASS: 
```
It starts up much quicker. Thank you.
