### DISCUSSION TITLE
Enable metrics_collector

### DISCUSSION THREAD

**Discussion by qibint** [docker-library/rabbitmq#624] [General]
Hello, we're using RabbitMQ Cluster Kubernetes Operator and created the rabbitmq instances from it attached is the yaml file.
However, I can't update disable_metrics_collector value to **true** through the additionalConfig since this management_agent.disable_metrics_collector.conf file in lines

https://github.com/docker-library/rabbitmq/blob/master/Dockerfile-alpine.template#L298-L299
https://github.com/docker-library/rabbitmq/blob/master/Dockerfile-ubuntu.template#L292-L295

always takes the priority over the 90-userDefinedConfiguration.conf file. Can you help with this problem?

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: amqp-workers
spec:
  image: rabbitmq:3.11.10
  service:
    type: ClusterIP
  replicas: 3
  persistence:
    storage: 20Gi
    storageClassName: gp2
  rabbitmq:
    additionalConfig: |
      # https://www.rabbitmq.com/configure.html
      # management metrics can be disabled altogether
      management_agent.disable_metrics_collector = false
```
