### DISCUSSION TITLE
How to mount enabled_plugins to the service container in GitHub CI for enabling rabbitmq plugins

### DISCUSSION THREAD

**Discussion by ksdeekshith** [docker-library/rabbitmq#635] [Q&A] [answered]
My CI workflow job looks like this:
 ```
tests:
    name: Tests
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}
    env:
      STOMP_CONNECTION_STRING: "stomp://guest:guest@clair-rabbitmq:61613"
    services:
      clair-rabbitmq:
        image: rabbitmq:3.8.5
        env:
          RABBITMQ_VM_MEMORY_HIGH_WATERMARK: "85%"

    strategy:
      matrix:
        go: ${{ fromJSON(needs.config.outputs.go_versions) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/go-cache
        with:
          go: ${{ matrix.go }}
      - run: go test -tags integration ./...
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: workspace-${{matrix.go}}
          path: ${{ github.workspace }}
```
How can I mount the enabled_plugins file to the service container here? 

Can anyone help me here, Please?
