### DISCUSSION TITLE
Unable to connect to RabbitMQ via localhost or 127.0.0.1

### DISCUSSION THREAD

**Discussion by zN3utr4l** [docker-library/rabbitmq#646] [Q&A] [answered]
### Describe the bug

I am encountering an issue when trying to connect to RabbitMQ using localhost or 127.0.0.1. I am running it within a Docker container that is on the same network as RabbitMQ server. However, I can only connect using the container Docker's IP address.

I have checked the output of the "rabbitmq-diagnostics listeners" command and noticed that RabbitMQ is configured to listen on all IPv6 interfaces. However, it seems that it is not configured to listen on IPv4 interfaces such as localhost or 127.0.0.1.

```
Interface: [::], port: 15692, protocol: http/prometheus, purpose: Prometheus exporter API over HTTP
Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: [::], port: 15672, protocol: http, purpose: HTTP API
```

I have tried modifying the RabbitMQ configuration to include localhost and 127.0.0.1 as listening interfaces in the configuration file, but without success. I used the following configurations:
```
listeners.tcp.default = 5672
listeners.ssl.default = 5671
loopback_users.guest = true
```

or

```
listeners.tcp.1= 127.0.0.1:5672
listeners.ssl.1= 127.0.0.1:5671
loopback_users.guest = true
```

```
/code # python rabbitmqadmin -H localhost -u guest -p guest list vhosts
*** Could not connect: [Errno 111] Connection refused

/code # python rabbitmqadmin -H 172.20.7 -u guest -p guest list vhosts
+------+----------+
| name | messages |
+------+----------+
| /    |          |
+------+----------+
```

### Describe the bug

I am encountering an issue when trying to connect to RabbitMQ using localhost or 127.0.0.1. I am running it within a Docker container that is on the same network as RabbitMQ server. However, I can only connect using the container Docker's IP address.

I have checked the output of the "rabbitmq-diagnostics listeners" command and noticed that RabbitMQ is configured to listen on all IPv6 interfaces. However, it seems that it is not configured to listen on IPv4 interfaces such as localhost or 127.0.0.1.

```
Interface: [::], port: 15692, protocol: http/prometheus, purpose: Prometheus exporter API over HTTP
Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
Interface: [::], port: 15672, protocol: http, purpose: HTTP API
```

I have tried modifying the RabbitMQ configuration to include localhost and 127.0.0.1 as listening interfaces in the configuration file, but without success. I used the following configurations:
```
listeners.tcp.default = 5672
listeners.ssl.default = 5671
loopback_users.guest = true
```

or

```
listeners.tcp.1= 127.0.0.1:5672
listeners.ssl.1= 127.0.0.1:5671
loopback_users.guest = true
```

```
/code # python rabbitmqadmin -H localhost -u guest -p guest list vhosts
*** Could not connect: [Errno 111] Connection refused

/code # python rabbitmqadmin -H 172.20.7 -u guest -p guest list vhosts
+------+----------+
| name | messages |
+------+----------+
| /    |          |
+------+----------+
/code # python rabbitmqadmin -H 127.0.0.1 -u guest -p guest list vhosts
*** Could not connect: [Errno 111] Connection refused
``` 

![image](https://github.com/docker-library/rabbitmq/assets/73225008/83298738-78a2-4589-b55d-d94a03215145)

/code # python rabbitmqadmin -H 127.0.0.1 -u guest -p guest list vhosts
*** Could not connect: [Errno 111] Connection refused
``` 

![image](https://github.com/docker-library/rabbitmq/assets/73225008/83298738-78a2-4589-b55d-d94a03215145)

**Comment by zN3utr4l** [comment]
the problem occurred while using this library https://github.com/revsys/django-health-check/issues/369#issue-1748036211

**Comment by lukebakken** [comment]
Hello, thanks for using RabbitMQ.

Please provide a docker compose project that starts containers in exactly the same way you do, using the same configuration. Right now you're asking us to guess at how to reproduce this problem, which takes time away from actually diagnosing it, and also usually leads to errors on our part.

I should be able to clone a git repository and run  `docker compose up --build` to start everything.

If you are unfamiliar with docker compose, then provide a means for us to start these containers the same way you are. A script is ideal.

**Comment by zN3utr4l** [comment]
```
version: "3"

services:
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "15672:15672"
        networks:
            mynetwork:
                ipv4_address: 172.20.2.2

    debian:
        image: debian
        networks:
            mynetwork:
                ipv4_address: 172.20.2.3
        command: >
            bash -c "
              apt-get update && apt-get install -y python3 curl && \
              curl http://172.20.2.2:15672/cli/rabbitmqadmin > rabbitmqadmin && \
              chmod +x rabbitmqadmin && \
              python3 rabbitmqadmin -H rabbitmq -u guest -p guest list vhosts && \
              python3 rabbitmqadmin -H 172.20.2.2 -u guest -p guest list vhosts && \
              python3 rabbitmqadmin -H 127.0.0.1 -u guest -p guest list vhosts && \
              python3 rabbitmqadmin -H localhost -u guest -p guest list vhosts
            "
        depends_on:
            rabbitmq:
                condition: service_started

networks:
    mynetwork:
        name: mynetwork
        ipam:
            config:
                - subnet: 172.20.2.0/24
```

`docker compose -f docker-compose.yml up -d`

the first 2 test commands with rabbitmqadmin work, the last 2 don't
