### DISCUSSION TITLE
Deployment to various CD/CD environments with alterating default user and password

### DISCUSSION THREAD

**Discussion by v-bulynkin** [docker-library/rabbitmq#659] [Q&A] [answered]
Hello, please suggest me the sensible way to achieve the following:

There are 3 environments in Gitlab - DEV, STAGE and PROD. I have a `definitions.json` file where a lot of queues and bindings are set.
I know that `$RABBITMQ_DEFAULT_USER` and `$RABBITMQ_DEFAULT_PASS` variables are ignored when `definitions.json` is used and templating the `definitons.json` file [is not supported](https://github.com/docker-library/rabbitmq/issues/365#issuecomment-1671349441).
However, I need to use different default user and password in each environment.

The obvious way is duplicating `definitions.json` to various _Gitlab CI/CD file variables_ and mounting those files as secrets in appropriate containers. However, it's uncomfortable to edit something in `definitions.json`, moreover, it should be done several times if I need to add another queue.

Is there any way to use environment variables in this case?
Or perhaps split definitions.json into 2 parts - one will be in the project and contain queues and similar stuff and the second in _Gitlab CI/CD file variables_ and contains only users/permissions/policies?
Maybe, there is another option I overlooked?

**Comment by lukebakken** [comment]
> Is there any way to use environment variables in this case?

Yes, you can use environment variables in the `rabbitmq.conf` file: https://www.rabbitmq.com/configure.html#env-variable-interpolation

Let me know if that works for you.

**Reply by v-bulynkin** [reply]
Thank you! What to do with "users" and "permissions" sections in `definitions.json`? Simply remove them?

I tried the following:

`definitions.json`, a part (only vhosts, queues,exchanges and bindings are presented)

``` json
  "vhosts":[
    {"name": "/"}
  ],
  "queues": [
    {
      "name": "lk.catalog_template",
      "vhost": "/",
      "durable": true,
      "auto_delete": false,
      "arguments": {
        "x-ha-policy": "all"
      }
    },
```

rabbitmq.conf:
```
default_user = $(RABBITMQ_DEFAULT_USER)
default_pass = $(RABBITMQ_DEFAULT_PASS)
load_definitions = /etc/rabbitmq/definitions.json
```
Dockerfile:
```
FROM rabbitmq:management-alpine
COPY --chown=rabbitmq:rabbitmq rabbitmq.conf /etc/rabbitmq/
COPY --chown=rabbitmq:rabbitmq definitions.json /etc/rabbitmq/
```

docker-compose.yml ($RABBITMQ_USER and $RABBITMQ_PASS are in the Gitlab CI variables)
``` yaml
version: "3.9"
services:
  rabbitmq:
    image: ${IMAGE_NAME}:${VERSION}
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_ADMIN_PORT}:15672
    volumes:
      - ${RABBITMQ_STORAGE}:/var/lib/rabbitmq
    networks:
      - rabbitmq

networks:
  rabbitmq:
    external: true
    name: ${NETWORK}
```

And no luck:
```
2023-08-10 07:05:49.245505+00:00 [warning] <0.932.0> HTTP access denied: user 'admin' - invalid credentials
```
