### DISCUSSION TITLE
Is there a way to decouple the UI from the broker?

### DISCUSSION THREAD

**Discussion by samuel-andres** [docker-library/rabbitmq#703] [Q&A] [answered]
```yaml
# compose.yaml

services:
  ...
  
  broker:
    hostname: broker
    image: rabbitmq:3.13.3-alpine
    ports:
      - 5672:5672
    volumes:
      - broker-data:/var/lib/rabbitmq

  broker-gui:
    image: rabbitmq:3.13.3-management-alpine
    profiles:
      - gui
    ports:
      - 15672:15672
  ...

volumes:
  ...
  broker-data:
  ...

```

I would like have a setup like this working, so I don't have the UI running always, but if I need to check something I can do `docker compose up broker-gui`. With the given config the broker gui starts it own rabbitmq server and I can't connect to the actual broker, is there a way to do this or the only way is to run it in a single service/container?
