### ISSUE TITLE
Setting environment variables for default vhost, user, pass causes rabbitmq to crash on startup

### ISSUE THREAD

**Issue by dsaborg** [docker-library/rabbitmq#127]
When I set environment variables for rabbitmq's default vhost, user or password it crashes on startup.

> sensu-rabbitmq_1  | /usr/local/bin/docker-entrypoint.sh: line 262: /etc/rabbitmq/rabbitmq.config: Permission denied
> sensu-rabbitmq_1 exited with code 1

I've set the variables in docker-compose.yml like so:

```
services:
  ...
  sensu-rabbitmq:
    ...
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret
```

Versions:

- Docker version 1.12.1, build 23cf638
- docker-compose version 1.9.0, build 2585387
- Running on Ubuntu 16.10

Note, this all works if you remove all three environment variables from docker-compose.
