### ISSUE TITLE
Special characters in RABBITMQ_DEFAULT_PASS triggers error

### ISSUE THREAD

**Issue by deargonaut** [docker-library/rabbitmq#199]
As issue mentions, while setting a harder password on DEFAULT_PASS with special characters it will trigger this error on startup.

```{"could not start kernel pid",application_controller,"error in config file \"/etc/rabbitmq/rabbitmq.config\" (6): syntax error before: RmkUkNsgRdg"}```

Would be nice to have safer password.

**Comment by michaelklishin** [comment]
@deargonaut you have provided no specific examples but I'm quite sure it's a shell escaping problem. As long as this image uses ENV variables heavily, there will be issues like that.

Use [definitions import](http://www.rabbitmq.com/management.html) with which values won't go through shell interpretation.

**Comment by tianon** [comment]
Indeed -- definitions import is a much safer bet.  However, if there's a specific example which causes problems (a full `docker run` line to reproduce would be best), I'd be keen to try debugging and fixing it.

@michaelklishin I suppose issues like this are probably a good answer to the question I've postulated in https://github.com/docker-library/rabbitmq/pull/197 about whether to still support so many envs in 3.7+ or whether to trim things down :smile:

**Comment by michaelklishin** [comment]
@tianon I support the interest to switch away from ENV variables and promote definition import along the way, even though it doesn't cover every area. I think definition import fits the immutable container as a unit of deployment idea very well.

Happy to discuss what options are available wherever you prefer (#197, a mailing list, on Slack or Zoom).

**Comment by tianon** [comment]
I think discussing that over on https://github.com/docker-library/rabbitmq/pull/197 would probably be preferable, but can do something else if you'd rather.  We like to keep the chat in GitHub as much as possible so that we can refer back to it later when we inevitably forget. :sweat_smile:

**Comment by deargonaut** [comment]
I am sorry, I should have added some example :)

I used in a docker-compose.yml like this:
```
version: '3'
services:
  rabbitMQ:
    image: rabbitmq:3.6-management
    volumes:
      - "./rabbitmq_data:/var/lib/rabbitmq"
    deploy:
      labels:
        [...]
    ports:
      [...]
    environment:
      - RABBITMQ_DEFAULT_USER=default
      - RABBITMQ_DEFAULT_PASS='9%QDEBvp@W!jA@n#EWVW'
      - RABBITMQ_ERLANG_COOKIE=xgFDbPJCqUumsBdqc
    networks:
      - frontend
      - backend

networks:
  backend:
    external:
      name: rabbitmq-network
  frontend:
    external:
      name: frontend
```

This gave the error on 
{"could not start kernel pid",application_controller,"error in config file \"/etc/rabbitmq/rabbitmq.config\" (6): syntax error before: **[password until special character]**"}

So this is probably indeed an issue with escaping, despite the single (or double) quotes around the password.
