### ISSUE TITLE
Management version does not have Python or rabbitmqadmin installed

### ISSUE THREAD

**Issue by greggilbert** [docker-library/rabbitmq#207]
The current 3.6-management branch is missing rabbitmqadmin and Python.

Using this docker-compose:
```
version: '3'
services:
  queue:
    image: rabbitmq:3.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
```

Here's my terminal:
```
$ docker-compose up -d
Pulling queue (rabbitmq:3.6-management)...
3.6-management: Pulling from library/rabbitmq
bc95e04b23c0: Pull complete
(...other stuff)
Digest: sha256:3840069fcc704db533cd83ec7fad30daabdd2fda321df4fb788b81b6ed2323b2
Status: Downloaded newer image for rabbitmq:3.6-management
Creating test_queue_1 ...
Creating test_queue_1 ... done

$ docker-compose exec queue /bin/bash
root@f2e677eafa1c:/# rabbitmq
root@f2e677eafa1c:/# which rabbitmqadmin
root@f2e677eafa1c:/# which python
root@f2e677eafa1c:/# echo $?
1
```

Given that rabbitmqadmin is a Python script, I can't see how this would work.

Did something change, or am I doing something wrong?
