### ISSUE TITLE
rabbitmq.config clobbered every run

### ISSUE THREAD

**Issue by mdebord1** [docker-library/rabbitmq#210]
I have a fully written `.config` file for rabbit and am spinning up the container via a compose file. 

Issue is that the rabbitmq.config file that is mounted as a volume file is getting overwritten with default values at the start of the container. 

Here is my docker-compose file: 
```
services:
  rabbitmq01s:
    image: rabbitmq:3.6.14-management
    volumes:
      - /dockerdata/volumes/rabbitmq01/def.json:/etc/rabbitmq/def.json
      - /dockerdata/volumes/rabbitmq01/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - /dockerdata/volumes/rabbitmq01/rabbit.mysite.key:/etc/rabbitmq/rabbit.mysite.key
      - /dockerdata/volumes/rabbitmq01/rabbit.mysite.crt:/etc/rabbitmq/rabbit.mysite.crt
    hostname: rabbitmq
    domainname: myhost.com
    environment:
      - RABBITMQ_DEFAULT_USER=someuser
      - RABBITMQ_DEFAULT_PASS=somepassword
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
```

I have the `.config` file configured like this: 
```
[
  { rabbit, [
    { tcp_listeners, [ 5672 ] }
  ]},
  {rabbitmq_management, [
    {load_definitions, "/etc/rabbitmq/def.json"},
    {listener, [{port, 15672}, {ip, "0.0.0.0"}, {ssl, true},
    {ssl_opts, [
       {certfile, "/etc/rabbitmq/rabbit.mysite.crt"},
       {keyfile, "/etc/rabbitmq/rabbit.mysite.key"}]}
  ]}]}
].
```

Once I start the container, the config gets clobbered. 
This is what it looks like after starting the container: 
```
[
	{ rabbit, [
		{ loopback_users, [ ] },
		{ tcp_listeners, [ 5672 ] },
		{ ssl_listeners, [ ] },
		{ default_pass, <<"password">> },
		{ default_user, <<"user">> },
		{ hipe_compile, false }
	] },
	{ rabbitmq_management, [ { listener, [
		{ port, 15672 },
		{ ssl, false }
	] } ] }
].
```

### **Why is my volume based config file being overwritten, and how can I stop it from doing so?!**
