### ISSUE TITLE
if an existing config file doesn't end with a newline, entrypoint appends to existing line

### ISSUE THREAD

**Issue by joekohlsdorf** [docker-library/rabbitmq#250]
**Affected version:** 3.7.4

**Steps to reproduce:**
Have an existing `/etc/rabbitmq/rabbitmq.conf` which doesn't end with a newline:
```
# i am an existing line in rabbitmq.conf
```

**Observed behaviour:**
When running the container, the entrypoint will do it's magic and add its defaults and I end up with this configuration file:
```
# i am an existing line in rabbitmq.conftotal_memory_available_override_value = 805306368
vm_memory_high_watermark.relative = 0.800
listeners.tcp.default = 5672
hipe_compile = false
management.listener.port = 15672
management.listener.ssl = false
```

Now you could argue that I should just put a newline at the end of my line and be done with it but in reality I am generating the file from a Kubernetes configmap which makes this exercise harder:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    # i am an existing line in rabbitmq.conf
```
Also, IDEs tend to get rid of that trailing newline.

**Comment by tianon** [comment]
Every IDE I use _adds_ the trailing newline for me (many doing so transparently without informing me that it's even happened), and I've even seen assemblers with differing behavior based on whether the trailing newline exists or not, but I digress.

The k8s config use case is one that resonates, especially since Docker's own config/secrets functionality can act similarly depending on how the config/secret objects are created.

It's untested, but the following patch should do the trick:

```diff
diff --git a/3.7/docker-entrypoint.sh b/3.7/docker-entrypoint.sh
index 99ae42b..b83351e 100755
--- a/3.7/docker-entrypoint.sh
+++ b/3.7/docker-entrypoint.sh
@@ -214,6 +214,11 @@ rabbit_set_config() {
 		"s/^[[:space:]]*(${sedKey}[[:space:]]*=[[:space:]]*)\S.*\$/\1${sedVal}/" \
 		"$newConfigFile"
 	if ! grep -qE "^${sedKey}[[:space:]]*=" "$newConfigFile"; then
+		if [ -n "$(tail -c1 "$newConfigFile")" ]; then
+			# file supplied by user is missing a trailing newline!  let's add one so the following append works properly
+			# https://github.com/docker-library/rabbitmq/issues/250
+			echo >> "$newConfigFile"
+		fi
 		echo "$key = $val" >> "$newConfigFile"
 	fi
 }
```

**Comment by joekohlsdorf** [comment]
Other solution:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |+
    # i am an existing line in rabbitmq.conf
```

I'll close this issue as this is really an error on the user-side.
