### ISSUE TITLE
Problem storing data

### ISSUE THREAD

**Issue by Fuddi** [docker-library/rabbitmq#286]
We are having a problem storing data, when RabbitMQ is setup in clustering mode. Is there any guide or example on doing that?

Thanks in advance.

**Comment by wglambert** [comment]
Is this what you're looking for http://josuelima.github.io/docker/rabbitmq/cluster/2017/04/19/setting-up-a-rabbitmq-cluster-on-docker.html
>RabbitMQ will save all the data to /var/lib/rabbitmq inside your container, so it’s a good idea to map this folder to a local folder on your host.

This is mentioned briefly in the docs
https://github.com/docker-library/docs/tree/master/rabbitmq#running-the-daemon
>Note the `database dir` there, especially that it has my "Node Name" appended to the end for the file storage. This image makes all of `/var/lib/rabbitmq` a volume by default.

**Comment by Fuddi** [comment]
Thanks for your reply.

The problem we have is, we are trying to run cluster in a docker swarm. That cluster use external network, because some other services need to use it. We managed to make a cluster and the whole solution works, but we have a problem with the persistent using docker volume. 

We try setting hostname for each node, but then the clustering fails, by making separate cluster for each node. 

Persistency works only if we disable external network. Example of our yml file is bellow.

```yaml
version: '3.5'

services:

  rabbitmq1:
    image: danskespil/bis-core-rabbitmq:{{ deploymentVersion }}
    hostname: "rabbitmq1"
    ports:
    - "15672:15672"
    - "5672:5672"
    volumes:
    - /tmp/bis-rabbitmq1:/var/lib/rabbitmq
    networks:
    - local
    - rabbit
    environment:
    - LOGSPOUT=ignore
    - RABBITMQ_USER=dev
    - RABBITMQ_PASSWORD=devtest
    - RABBITMQ_ERLANG_COOKIE=cc6f570d-8d7b-47fc-a002-b3c2b336b01e
    - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
    deploy:
      replicas: 1

  rabbitmq2:
    image: danskespil/bis-core-rabbitmq:{{ deploymentVersion }}
    hostname: "rabbitmq2"
    volumes:
    - /tmp/bis-rabbitmq2:/var/lib/rabbitmq
    networks:
    - local
    - rabbit
    environment:
    - LOGSPOUT=ignore
    - RABBITMQ_USER=dev
    - RABBITMQ_PASSWORD=devtest
    - RABBITMQ_ERLANG_COOKIE=cc6f570d-8d7b-47fc-a002-b3c2b336b01e
    - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
    ports:
    - "5672"
    deploy:
      replicas: 1

  rabbitmq3:
    image: danskespil/bis-core-rabbitmq:{{ deploymentVersion }}
    hostname: "rabbitmq3"
    volumes:
    - /tmp/bis-rabbitmq3:/var/lib/rabbitmq
    networks:
    - local
    - rabbit
    environment:
    - LOGSPOUT=ignore
    - RABBITMQ_USER=dev
    - RABBITMQ_PASSWORD=devtest
    - RABBITMQ_ERLANG_COOKIE=cc6f570d-8d7b-47fc-a002-b3c2b336b01e
    - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
    ports:
    - "5672"
    deploy:
      replicas: 1

  consul:
    image: consul
    hostname: "consul"
    ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53"
    networks:
    - local
    deploy:
      replicas: 1

networks:
  local:
    driver: overlay
  rabbit:
    external: true
```
