### ISSUE TITLE
Slow startup and teardown

### ISSUE THREAD

**Issue by sharksforarms** [docker-library/rabbitmq#293]
It seems like the rabbit image takes fairly long to startup and teardown, is there anything I can disable to speed this process up? I am using it with docker-compose for system testing (fresh container for every test)

**Comment by wglambert** [comment]
How involved is your startup process? using this docker-compose.yml it finishes starting in about 3 seconds.
```yml
version: '3'

services:
 rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
```

```console
$ docker-compose up
Creating network "rabbitmq-293_default" with the default driver
Creating rabbitmq-293_rabbitmq_1 ... done
Attaching to rabbitmq-293_rabbitmq_1
rabbitmq_1  | 2018-11-30 19:17:32.775 [info] <0.33.0> Application lager started on node rabbit@rabbitmq
. . .
rabbitmq_1  |  completed with 3 plugins.
rabbitmq_1  | 2018-11-30 19:17:35.666 [info] <0.5.0> Server startup complete; 3 plugins started.
```

I'd recommend going through your `docker-compose logs` for anything that's taking an excessive amount of time and troubleshooting it over at [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability
