### ISSUE TITLE
Generic server rabbit_disk_monitor terminating 

### ISSUE THREAD

**Issue by aidanlane** [docker-library/rabbitmq#32]
Hi guys,

Any thoughts on what I could be doing wrong?

Dockerfile
```
FROM rabbitmq:3-management
EXPOSE 5672
```

docker-compose.yml
```
data:
  image: busybox
  volumes:
   - /var/lib/mysql
   - db/mysql/:/temp/mysql/
   - .:/var/www/html/
web:
  build: Dockerfiles/php-apache/
  environment:
    IS_DOCKER: true
  ports:
    - "80:80"
    - "9000:9000"
  dns: 8.8.8.8
  links:
    - db
    - memcache
    - rabbitmq
    - svgtex
    - elasticsearch
  volumes_from:
    - data
db:
  build: Dockerfiles/mysql/
  volumes_from:
   - data
  environment:
    MYSQL_DATABASE: wordpress_db
    MYSQL_ROOT_PASSWORD: root
    STARTUP_SQL: /temp/mysql/dumb.sql
rabbitmq:
  build: Dockerfiles/rabbitmq/
  ports:
    - "5000:15672"
    - "5672:5672"
svgtex:
  build: Dockerfiles/svgtex
  ports:
    - "16000:16000"
elasticsearch:
  build: Dockerfiles/elasticsearch/
  ports:
    - "9200:9200"
    - "9300:9300"
memcache:
  image: memcached
```

boot2docker version:
```
Boot2Docker-cli version: v1.7.0
Git commit: 7d89508
```

docker version
```
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

docker-compose --version
```
docker-compose version: 1.3.1
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zf 19 Mar 2015
```

On first request to the web server:
```
rabbitmq_1      | 
rabbitmq_1      |               RabbitMQ 3.5.3. Copyright (C) 2007-2014 GoPivotal, Inc.
rabbitmq_1      |   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
rabbitmq_1      |   ##  ##
rabbitmq_1      |   ##########  Logs: tty
rabbitmq_1      |   ######  ##        tty
rabbitmq_1      |   ##########
rabbitmq_1      |               Starting broker...
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:21 ===
rabbitmq_1      | Starting RabbitMQ 3.5.3 on Erlang 17.5.3
rabbitmq_1      | Copyright (C) 2007-2014 GoPivotal, Inc.
rabbitmq_1      | Licensed under the MPL.  See http://www.rabbitmq.com/
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:21 ===
rabbitmq_1      | node           : rabbit@0b49754b7dd6
rabbitmq_1      | home dir       : /var/lib/rabbitmq
rabbitmq_1      | config file(s) : /etc/rabbitmq/rabbitmq.config
rabbitmq_1      | cookie hash    : qogj0q51xp1ftTJ3mF7wOA==
rabbitmq_1      | log            : tty
rabbitmq_1      | sasl log       : tty
rabbitmq_1      | database dir   : /var/lib/rabbitmq/mnesia/rabbit@0b49754b7dd6
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:21 ===
rabbitmq_1      | Memory limit set to 398MB of 996MB total.
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:21 ===
rabbitmq_1      | Disk free limit set to 50MB
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | Limiting to approx 1048476 file handles (943626 sockets)
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      |     application: mnesia
rabbitmq_1      |     exited: stopped
rabbitmq_1      |     type: temporary
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | Priority queues enabled, real BQ is rabbit_variable_queue
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | Adding vhost '/'
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | Creating user 'guest'
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | Setting user tags for user 'guest' to [administrator]
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | Setting permissions for 'guest' in '/' to '.*', '.*', '.*'
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | msg_store_transient: using rabbit_msg_store_ets_index to provide index
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | msg_store_persistent: using rabbit_msg_store_ets_index to provide index
rabbitmq_1      | 
rabbitmq_1      | =WARNING REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | msg_store_persistent: rebuilding indices from scratch
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | started TCP Listener on [::]:5672
rabbitmq_1      |  completed with 0 plugins.
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | Server startup complete; 0 plugins started.
rabbitmq_1      | 
rabbitmq_1      | =INFO REPORT==== 8-Jul-2015::07:05:22 ===
rabbitmq_1      | accepting AMQP connection <0.301.0> (172.17.0.7:47078 -> 172.17.0.5:5672)
rabbitmq_1      | 
rabbitmq_1      | =ERROR REPORT==== 8-Jul-2015::07:07:13 ===
rabbitmq_1      | ** Generic server rabbit_disk_monitor terminating 
rabbitmq_1      | ** Last message in was update
rabbitmq_1      | ** When Server state == {state,"/var/lib/rabbitmq/mnesia/rabbit@0b49754b7dd6",
rabbitmq_1      |                                50000000,16345931776,100,10000,
rabbitmq_1      |                                #Ref<0.0.0.1735>,false}
rabbitmq_1      | ** Reason for termination == 
rabbitmq_1      | ** {{unparseable,[]},
rabbitmq_1      |     [{rabbit_disk_monitor,parse_free_unix,1,[]},
rabbitmq_1      |      {rabbit_disk_monitor,internal_update,1,[]},
rabbitmq_1      |      {rabbit_disk_monitor,handle_info,2,[]},
rabbitmq_1      |      {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},
rabbitmq_1      |      {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},
rabbitmq_1      |      {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
rabbitmq_1      | 
rabbitmq_1      | =CRASH REPORT==== 8-Jul-2015::07:07:13 ===
rabbitmq_1      |   crasher:
rabbitmq_1      |     initial call: rabbit_disk_monitor:init/1
rabbitmq_1      |     pid: <0.77.0>
rabbitmq_1      |     registered_name: rabbit_disk_monitor
rabbitmq_1      |     exception exit: {unparseable,[]}
rabbitmq_1      |       in function  gen_server:terminate/7 (gen_server.erl, line 804)
rabbitmq_1      |     ancestors: [rabbit_disk_monitor_sup,rabbit_sup,<0.69.0>]
rabbitmq_1      |     messages: []
rabbitmq_1      |     links: [<0.76.0>]
rabbitmq_1      |     dictionary: []
rabbitmq_1      |     trap_exit: false
rabbitmq_1      |     status: running
rabbitmq_1      |     heap_size: 987
rabbitmq_1      |     stack_size: 27
rabbitmq_1      |     reductions: 26925
rabbitmq_1      |   neighbours:
rabbitmq_1      | 
rabbitmq_1      | =SUPERVISOR REPORT==== 8-Jul-2015::07:07:13 ===
rabbitmq_1      |      Supervisor: {local,rabbit_disk_monitor_sup}
rabbitmq_1      |      Context:    child_terminated
rabbitmq_1      |      Reason:     {unparseable,[]}
rabbitmq_1      |      Offender:   [{pid,<0.77.0>},
rabbitmq_1      |                   {name,rabbit_disk_monitor},
rabbitmq_1      |                   {mfargs,{rabbit_disk_monitor,start_link,[50000000]}},
rabbitmq_1      |                   {restart_type,{transient,1}},
rabbitmq_1      |                   {shutdown,4294967295},
rabbitmq_1      |                   {child_type,worker}]
```
