### ISSUE TITLE
vhost / not found

### ISSUE THREAD

**Issue by marksugar** [docker-library/rabbitmq#338]
Everything works fine when not using RABBITMQ_DEFAULT_VHOST

An error occurred after using the RABBITMQ_DEFAULT_VHOST variable. as follows

error log:
```
2019-05-28 09:26:19.441 [error] <0.675.0> Error on AMQP connection <0.675.0> (x.x.x.x:42420 -> x.x.x.x:5672 - rabbitConnectionFactory#f3398e7:6, user: 'admin', state: opening):
vhost / not found
2019-05-28 09:26:14.432 [info] <0.668.0> closing AMQP connection <0.668.0> (x.x.x.x:42308 -> x.x.x.x:5672 - rabbitConnectionFactory#f3398e7:5, vhost: 'none', user: 'admin')
```

compose.yml
```version: '3'
services:
  rabbitmq:
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
    container_name: rabbitmq
    restart: always
    privileged: true
    network_mode: host
    image: rabbitmq:3.7.15-management-alpine
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=YjJiOTY0NDAxNWRkNmI1Y2Yx
    - RABBITMQ_DEFAULT_VHOST=DSrabbitmq
    - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=1024MB
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/rabbitmq:/var/lib/rabbitmq
```
Now I use `- RABBITMQ_DEFAULT_VHOST=/`

thanks

**Comment by wglambert** [comment]
Your compose file works fine, also because you're doing `network_mode: host` the container's hostname will be the host's.
Setting the default vhost to `/` is the default when not specifying one at all

```console
$ docker-compose up -d
Creating rabbitmq ... done

$ curl -i -u admin:YjJiOTY0NDAxNWRkNmI1Y2Yx http://localhost:15672/api/vhosts
HTTP/1.1 200 OK
cache-control: no-cache
content-length: 90
content-security-policy: default-src 'self'
content-type: application/json
date: Thu, 30 May 2019 17:31:41 GMT
server: Cowboy
vary: accept, accept-encoding, origin

[{"cluster_state":{"rabbit@Ayanami-clone":"running"},"name":"DSrabbitmq","tracing":false}]

$ docker exec rabbitmq rabbitmqctl list_vhosts
Listing vhosts ...
name
DSrabbitmq
```

```yml
version: '3.3'

services:
  rabbitmq:
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
    container_name: rabbitmq
    restart: always
    network_mode: host
    image: rabbitmq:3.7.15-management-alpine
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=YjJiOTY0NDAxNWRkNmI1Y2Yx
    - RABBITMQ_DEFAULT_VHOST=DSrabbitmq
    - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=1024MB
```
