### ISSUE TITLE
RabbitMQ fails to start "no match of right hand value undefined in rabbit_priority_queue:enable/0"

### ISSUE THREAD

**Issue by w7089** [docker-library/rabbitmq#353]
[issue ](https://groups.google.com/forum/#!topic/rabbitmq-users/Dpl6uR3-LYQ) randomly happens in 3.7.4 and 3.7.16.

<details>

Dockerfile
```dockerfile
FROM rabbitmq:3.7.16

RUN apt-get update && apt-get -y install iputils-ping

COPY custom-docker-entrypoint.sh /custom-docker-entrypoint.sh

RUN mkdir -p /etc/customrabbitmq
COPY customrabbitmq.conf /etc/customrabbitmq/customrabbitmq.conf
RUN chmod -R 777 /etc/customrabbitmq

ENTRYPOINT ["/custom-docker-entrypoint.sh"]
```

custom-docker-entrypoint.sh
```bash
#!/bin/bash

sleep 18000 # 30 mins to allow for smooth restart
exec docker-entrypoint.sh rabbitmq-server
```

customrabbitmq.conf
```
cluster_partition_handling = pause_minority 
listeners.tcp.default = 5672

default_pass = root
default_user = pass 
hipe_compile =  false 
```

docker-compose.yml
```yaml
version: '3'
services:
  rabbitmq:
    hostname: "{{.Node.Hostname}}"
    deploy:
      mode: global
      restart_policy:
         delay: 10s
    image: docker.io/warrior7089/rabbitmq:1.0
    healthcheck:
        test: ["CMD-SHELL", "rabbitmqctl node_health_check"]        
        interval: 1m
        timeout: 30s
        retries: 10
    networks:
      - default
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-data-etc:/etc/rabbitmq
      - rabbitmq-data-var:/var/lib/rabbitmq    
    environment:              
      - RABBITMQ_LOG_BASE=/var/log/rabbitmq        
      - RABBITMQ_CONFIG_FILE=/etc/customrabbitmq/customrabbitmq.conf
      - RABBITMQ_ERLANG_COOKIE=ATKLALLROLGHWFVLNTBY
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
    logging:
      driver: "json-file"


volumes:
  rabbitmq-data-etc:
  rabbitmq-data-var:
```

Initialization script
```bash
docker pull warrior7089/rabbitmq:1.0
docker swarm init
docker stack deploy -c docker-compose.yml rab
docker exec -i $(docker ps -q -f 'name=rab_rabbitmq') bash -c 'echo -e $RABBITMQ_ERLANG_COOKIE > /var/lib/rabbitmq/.erlang.cookie'
docker exec -i $(docker ps -q -f 'name=rab_rabbitmq') bash -c 'chmod 600 /var/lib/rabbitmq/.erlang.cookie'
docker exec -i $(docker ps -q -f 'name=rab_rabbitmq') pkill sleep
sleep 5
docker exec -i $(docker ps -q -f 'name=rab_rabbitmq') rabbitmq-plugins enable rabbitmq_management
```

</details>
