### ISSUE TITLE
timezone invalid

### ISSUE THREAD

**Issue by lynings** [docker-library/rabbitmq#356]
## Environment
![image](https://user-images.githubusercontent.com/14272789/62199573-513eca00-b3b6-11e9-947a-47b09c3e3138.png)

## docker-compose.yml
```
version: "3"
services:

  rabbitmq:
    image: rabbitmq:3.7.17-alpine
    #    rabbitmqctl add_user user 123123; rabbitmqctl set_user_tags user administrator; rabbitmqctl set_permissions -p / user '.*' '.*' '.*'
    # 增加 command 导致 RABBITMQ_DEFAULT_USER 和 RABBITMQ_DEFAULT_PASS 无效
    command: sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &&
      echo $TZ > /etc/timezone &&
      rabbitmq-plugins enable --offline rabbitmq_management &&
      rabbitmq-server"
    hostname: rabbitmq
    volumes:
      - ddd-rabbitmqdata:/var/lib/rabbitmq
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 123123
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.3"
          memory: 256M
    ports:
      - "15672:15672"
    networks:
      - ddd-microservices

volumes:
  ddd-rabbitmqdata:
    external:
      name: ddd-rabbitmqdata
```

## Command
```
docker stack deploy -c docker-compose.yml mq
```

## Review
![image](https://user-images.githubusercontent.com/14272789/62199832-d1652f80-b3b6-11e9-99b9-50c7b39e31ec.png)
