### ISSUE TITLE
rabbitmqctl in docker: node not running at all

### ISSUE THREAD

**Issue by aliaksandr-master** [docker-library/rabbitmq#359]
I try to use any command in rabbitmqctl with docker
```yaml
# docker compose file
services:
  etl_broker:
    hostname: etl_broker
    image: rabbitmq:3.7-management
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: '123456'
      RABBITMQ_NODENAME: 'rabbitmq@etl_broker'
      RABBITMQ_DEFAULT_USER: someuser
      RABBITMQ_DEFAULT_PASS: somepass
    command: 'rabbitmq-server'
    ports:
      - 5672:5672
    expose:
      - 15672
    volumes:
      - etl_broker_volume:/var/lib/mnesia
```
start the server
```
docker-compose up -d
```
it works great. My services works correctly with rabbitmq. 

Everything is fine, but... When I want to check in `cmd` something

I open the `bash` inside
```bash
$ docker-compose run etl_broker bash
```
I am inside of container. And I do next:
```bash
# rabbitmqctl status
```
It return me this: 
```
Status of node rabbitmq@etl_broker ...
Error: unable to perform an operation on node 'rabbitmq@etl_broker'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbitmq@etl_broker
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: [rabbitmq@etl_broker]

rabbitmq@etl_broker:
  * connected to epmd (port 4369) on etl_broker
  * epmd reports: node 'rabbitmq' not running at all
                  no other nodes on etl_broker
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-12-rabbitmq@etl_broker'
 * effective user's home directory: /var/lib/rabbitmq
 * Erlang cookie hash: IivrhA2sAwoU3X7Arxre9g==
```
Erlang cookie set as env var. I checked it

I really don't know what going wrong =(
