### ISSUE TITLE
Enabling plugins through environment variable

### ISSUE THREAD

**Issue by hadmut** [docker-library/rabbitmq#371]
Hi,

the docs (chapter "Enabling Plugins") say that there's two ways to enable plugins, either through dockerfile/run or through mounting a /etc/rabbitmq/enabled_plugins file. 

Since this file contains just a single line, would be nice if it was possible to pass the contents just as an environment variable while starting.

**Comment by tianon** [comment]
This is something we *could* do, but we've been trying to reduce the number of things we add/do on top of a standard RabbitMQ distribution, so I'd rather not do this here.

Similar to the new `.ini`-style configuration file, this should be relatively easy to either provide as a bind-mount or do via a simple custom container command like `sh -c 'echo some-enabled-plugins-content > /etc/rabbitmq/enabled_plugins && exec docker-entrypoint.sh rabbitmq-server'`

**Comment by hadmut** [comment]
Well, 
compare how much effort it is to 

- create, store, distribute a proprietary docker image
- mount a file
- just pass an environment variable

Try to do it with automation tools like ansible or puppet. Passing an environment is a simple one-liner, just a paramenter, while the other two methods take several steps, some difficult and error-prone to automate. 

"easy to either provide" is a hacker's view, but not the view of an administrator who needs to put things together in an automated way, or to put things in swarms, kubernetes pods and things like that.

**Comment by tianon** [comment]
For a system like Kubernetes, you'd use something like this:

```yaml
  containers:
  - name: rabbitmq-container
    image: rabbitmq:3.7
    command: ["sh", "-c", "echo some-enabled-plugins-content > /etc/rabbitmq/enabled_plugins && exec docker-entrypoint.sh rabbitmq-server"]
```

Where `some-enabled-plugins-content` could easily even reference an environment variable if you really want to use an environment variable instead of `command:` for setting the value.
