### ISSUE TITLE
Issues with latest 3-management image

### ISSUE THREAD

**Issue by Ivers07** [docker-library/rabbitmq#377]
Hi,

I've had a container running the 3-management image for a few weeks without issue, then I tried to deploy a new container on a new docker host with the same compose file :
``` yaml
version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672 
      - 25672:25672    
```
 The image was pulled down and the container started however I was unable to access the management console at http://localhost:15672. I spotted in the logs that the management plugin was not loaded, so I ran the following commands:
``` ps
docker exec -it rabbitmq bash
```
```
rabbitmq-plugins enable rabbitmq_management
```

the plugin was enabled and then I could open the login screen at http://locahost:15672/. However, when I entered the default guest/guest, it said login was only possible when on the localhost, despite the fact that that was what I was doing.

I compared the container to one I had been running for a few weeks and I found that although the image tags were the same, the digest was different so it appears the images on docker hub were updated 4 days ago (24th/25th Oct). If I changed my compose file to target the previous digest I had been using e.g. rabbitmq@sha256:539ce50c25591ba1355b2f062829583d744ad529d499a15c530f71bd3d067bec then the image works as normal.

It appears the images pushed around 24th/25th October have issues on them.
