### ISSUE TITLE
RabbitMq Docker TLS Configuration certificat error

### ISSUE THREAD

**Issue by aelmalki** [docker-library/rabbitmq#382]
Hello,

I want to run an instance of RabbitMq with TLS support, i follow the official documentation and in generate certificat as mentionned by manualy open-ssl step-by-step, but i have thoses follwing errors :

**Browser error : _https://localhost:8000_** 
```
This CA Root certificate is not trusted because it is not in the Trusted Root Certification Authorities store.
```

**RabbitMq Docker logs :**
```
rabbitmq_1  | 2019-12-08 12:14:07.533 [info] <0.225.0> Running boot step pre_flight defined by app rabbit
rabbitmq_1  | 2019-12-08 12:14:07.534 [info] <0.225.0> Running boot step notify_cluster defined by app rabbit
rabbitmq_1  | 2019-12-08 12:14:07.534 [info] <0.225.0> Running boot step networking defined by app rabbit
rabbitmq_1  | 2019-12-08 12:14:07.539 [warning] <0.487.0> Setting Ranch options together with socket options is deprecated. Please use the new map syntax that allows specifying socket options separately from other options.
rabbitmq_1  | 2019-12-08 12:14:07.541 [info] <0.501.0> started TCP listener on [::]:5672
rabbitmq_1  | 2019-12-08 12:14:07.543 [warning] <0.502.0> Setting Ranch options together with socket options is deprecated. Please use the new map syntax that allows specifying socket options separately from other options.
rabbitmq_1  | 2019-12-08 12:14:07.545 [info] <0.517.0> started TLS (SSL) listener on [::]:5671
rabbitmq_1  | 2019-12-08 12:14:07.546 [info] <0.225.0> Running boot step direct_client defined by app rabbit
rabbitmq_1  | 2019-12-08 12:14:07.588 [info] <0.571.0> Management plugin: HTTPS listener started on port 15671
rabbitmq_1  | 2019-12-08 12:14:07.588 [info] <0.678.0> Statistics database started.
rabbitmq_1  |  completed with 3 plugins.
rabbitmq_1  | 2019-12-08 12:14:07.698 [info] <0.8.0> Server startup complete; 3 plugins started.
rabbitmq_1  |  * rabbitmq_management
rabbitmq_1  |  * rabbitmq_management_agent
rabbitmq_1  |  * rabbitmq_web_dispatch
rabbitmq_1  | 2019-12-08 12:14:39.559 [info] <0.687.0> TLS server: In state certify received CLIENT ALERT: Fatal - Certificate Unknown
rabbitmq_1  |
rabbitmq_1  | 2019-12-08 12:14:43.318 [info] <0.691.0> TLS server: In state certify received CLIENT ALERT: Fatal - Certificate Unknown
rabbitmq_1  |
rabbitmq_1  | 2019-12-08 12:14:43.384 [info] <0.700.0> TLS server: In state abbreviated received CLIENT ALERT: Fatal - Certificate Unknown
```
**My Docker compose file :**
```
version: '2'
services:
  rabbitmq:
      image: rabbitmq:3.7.14-management
      environment:
        RABBITMQ_DEFAULT_USER: "admino"
        RABBITMQ_DEFAULT_PASS: "password"
        RABBITMQ_DEFAULT_VHOST: "/"
        RABBITMQ_SSL_CACERTFILE: "/perso_ssl/ca_certificate.pem"
        RABBITMQ_SSL_CERTFILE: "/perso_ssl/server_certificate.pem"
        #RABBITMQ_SSL_KEYFILE: "/perso_ssl/server_key.pem"
        RABBITMQ_SSL_KEYFILE: "/perso_ssl/private_key.pem"
        RABBITMQ_SSL_PASSWORD: "mypass"
        RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "false"
        RABBITMQ_SSL_VERIFY: "verify_peer"
        RABBITMQ_MANAGEMENT_SSL_CACERTFILE: "/perso_ssl/ca_certificate.pem"
        RABBITMQ_MANAGEMENT_SSL_CERTFILE: "/perso_ssl/server_certificate.pem"
        RABBITMQ_MANAGEMENT_SSL_KEYFILE: "/perso_ssl/private_key.pem"
        RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT: "false"
        RABBITMQ_MANAGEMENT_SSL_VERIFY: "verify_peer"
        RABBITMQ_MANAGEMENT_SSL_PASSWORD: "mypass"
      ports:
        - 7000:15672
        - 7001:5672
        - 8000:15671
        - 8001:5671
      volumes:
        - C:\\RabbitMq_TLS\\certs:/perso_ssl
```

Have you any idea about this error ?

Thank you for your help !
