### ISSUE TITLE
docker-compose down data lost?

### ISSUE THREAD

**Issue by im-zhangxi** [docker-library/rabbitmq#395]
docker-compose

```
rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: rabbitmq
    restart: always
    ports:
      - "${RABBITMQ_HOST_PORT_C}:5672"
      - "${RABBITMQ_HOST_PORT_S}:15672"
    volumes:
      - ${DATA_DIR}/rabbitmq:/var/lib/rabbitmq:rw
      - ${RABBITMQ_LOG_DIR}:/var/log/rabbitmq:rw
    environment:
       TZ: "$TZ"
       RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
       RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
          - default
```

When I perform docker-compose down and up, data lost.  help me
