### ISSUE TITLE
Log settings are not read from rabbitmq.conf

### ISSUE THREAD

**Issue by arabelaa** [docker-library/rabbitmq#408]
I have the following rabbitmq.conf file 

```
loopback_users.guest = false
listeners.tcp.default = 5672
log.console.level = debug
log.file = rabbit.log
log.dir = /var/log/rabbitmq
log.file.level = debug
log.connection.level = debug
log.channel.level = debug
log.queue.level = debug
```

and Dockerfile 
```

FROM rabbitmq:3.8.3

# Update apt-get, install curl and unzip
RUN apt-get update && apt-get install -y curl unzip

# Download and unzip delayed messages plugin, also remove zip and move the plugin to the plugins folder
RUN curl https://dl.bintray.com/rabbitmq/community-plugins/3.8.x/rabbitmq_delayed_message_exchange/rabbitmq_delayed_message_exchange-20191008-3.8.x.zip > rabbitmq_delayed_message_exchange-20191008-3.8.x.zip && \
unzip rabbitmq_delayed_message_exchange-20191008-3.8.x.zip && \
rm -f rabbitmq_delayed_message_exchange-20191008-3.8.x.zip && \
mv rabbitmq_delayed_message_exchange-20191008-3.8.x.ez plugins/

COPY enabled_plugins /etc/rabbitmq/enabled_plugins
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf

# Enable the delayed message plugin
RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange

EXPOSE 1883/tcp
EXPOSE 15672/tcp
EXPOSE 5672/tcp
```

In my docker-compose.yml my service looks like

```

  mqtt:
    build: ./gateway-rabbitmq
    ports:
      - 1883:1883  #mqtt
      - 15672:15672 #management
      - 5672:5672 #amqp
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia

```

The log configurations are not picked up by the rabbitmq service. I find this very strange having into account the documentation I found - [here](https://www.rabbitmq.com/logging.html )

Any ideas what might be wrong?
