### ISSUE TITLE
Definitions file not loaded using management plugin on very first boot of Docker container

### ISSUE THREAD

**Issue by phillipuniverse** [docker-library/rabbitmq#428]
This seems to only happen on the very first boot of the Docker container, or when the container is removed on `docker-compose down` and then restarted. It is peculiar that if this happens _after_ the container has been created (or with a `docker-compose up -d --force-recreate`), the policies are loaded correctly.

Here's an example:

docker-compose.yml:
```yml
version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
```

rabbitmq_enabled_plugins
```erlang
[rabbitmq_management,rabbitmq_shovel,rabbitmq_shovel_management].
```

rabbitmq_definitions.json:
```json
{
  "policies":[
    {
      "vhost":"/",
      "name":"1wk Expiration",
      "pattern":".+(?<!.dlq)$",
      "apply-to":"queues",
      "definition":{
        "expires":604800000
      },
      "priority":0
    }
  ]
}
```

rabbitmq.conf
```conf
loopback_users.guest = false
default_vhost = /
default_user = guest
default_pass = guest
default_permissions.configure = .*
default_permissions.read = .*
default_permissions.write = .*
management.load_definitions = /etc/rabbitmq/rabbitmq_definitions.json
```

If I change the `management.load_definitions` to instead be `load_definitions`, then it works but only if an entire initial export was done via a [definition export](https://www.rabbitmq.com/definitions.html#export). Example working json with using `load_definitions=...` in the `.conf` file:

```json
{
  "rabbit_version":"3.8.2",
  "rabbitmq_version":"3.8.2",
  "users":[
    {
      "name":"guest",
      "password_hash":"NnOJMfR7/f8OAs2T4vR6KUXNle/f7oBVifv7ksvqR7xtnnuX",
      "hashing_algorithm":"rabbit_password_hashing_sha256",
      "tags":"administrator"
    }
  ],
  "vhosts":[
    {
      "name":"/"
    }
  ],
  "permissions":[
    {
      "user":"guest",
      "vhost":"/",
      "configure":".*",
      "write":".*",
      "read":".*"
    }
  ],
  "topic_permissions":[ ],
  "parameters":[ ],
  "global_parameters":[
    {
      "name":"cluster_name",
      "value":"rabbit@rabbitmq"
    }
  ],
  "policies":[
    {
      "vhost":"/",
      "name":"1wk Expiration",
      "pattern":".+(?<!.dlq)$",
      "apply-to":"queues",
      "definition":{
        "expires":604800000
      },
      "priority":0
    }
  ],
  "queues":[ ],
  "exchanges":[ ],
  "bindings":[ ]
}
```
