### ISSUE TITLE
Volume mount is causing plugins to not load

### ISSUE THREAD

**Issue by RyannnnnnR** [docker-library/rabbitmq#439]
Hi,
Running this docker-compose snippet:
```
  rabbitmqserver:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmqserver
    hostname: 'rabbit-mq-host'
    volumes:
      - "$PWD/.docker/rabbitmq/etc/:/etc/rabbitmq/"
      - "$PWD/.docker/rabbitmq/data/:/var/lib/rabbitmq/"
      - "$PWD/.docker/rabbitmq/logs/:/var/log/rabbitmq/"
    ports:
      - 5672:5672
      - 15672:15672
```
Results in this: 
```
rabbitmqserver | 2020-09-17 09:07:27.257 [info] <0.696.0> started TCP listener on [::]:5672
rabbitmqserver | 2020-09-17 09:07:27.431 [info] <0.681.0> Server startup complete; 0 plugins started.
rabbitmqserver | completed with 0 plugins.
```
This obviously results in  the management plugin not running and therefore not being accesible.

The only thing in the mount point is the config file:
![image](https://user-images.githubusercontent.com/26314009/93450373-3fe9b180-f919-11ea-85a7-de3895023ed0.png)

The docker following docker run command produces the same result:
`docker run --rm -it --hostname my-rabbit -v "$PWD/.docker/rabbitmq/etc/:/etc/rabbitmq/" -p 15672:15672 -p 5672:5672 rabbitmq:3.7-management-alpine` --  I tried this command with all three mount points and only observed an error when this above mount point was attached.

I'm on MacOS 10.15.6.

Please let me  know if i've missed anything.
Thanks
