### ISSUE TITLE
The restart policy not working with docker-compose

### ISSUE THREAD

**Issue by Mr-LiuDC** [docker-library/rabbitmq#444]
I have set the container restart policy with docker-compose. When I restart the docker host machine, after a while the docker daemon auto started up and also my spring boot application container auto started, but rabbitmq container not.

Here is my rabbitmq docker-compose.yml file
```
  rabbitmq:
    image: rabbitmq:3.8.3-management
    hostname: ${RABBITMQ_NODENAME}
    container_name: rabbitmq_management
    environment:
      RABBITMQ_DEFAULT_USER: rplus_refactor
      RABBITMQ_DEFAULT_PASS: Rplus_2019
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 70%
      RABBITMQ_NODENAME: rabbitmq@${RABBITMQ_NODENAME}
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - /opt/docker_data/rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 4369:4369
      - 5672:5672
      - 15672:15672
      - 25672:25672
    restart: on-failure:3
```
