### ISSUE TITLE
High usage of PV in Kubernetes without load on rabbitmq

### ISSUE THREAD

**Issue by 0m1xa** [docker-library/rabbitmq#503]
Hi!
I'm running rabbitmq (rabbitmq:3.8.19-alpine) on Kubernetes and have a question about using of PV by rabbitmq image.
First of all, we need to create resources from a manifest.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: rabbit-single
    namespace: rabb
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        service: rabbitmq
    name: rabbit-single
    namespace: rabb
spec:
    replicas: 1
    selector:
        matchLabels:
            service: rabbitmq
    strategy: {}
    template:
        metadata:
            labels:
                service: rabbitmq
        spec:
            containers:
                - image: rabbitmq:3.8.19-alpine
                  name: rabbitmq
                  resources: {}
                  ports:
                      - containerPort: 15692
                        protocol: TCP
                      - containerPort: 5692
                        protocol: TCP
                  volumeMounts:
                      - mountPath: /var/lib/rabbitmq
                        name: rabbitmq
            volumes:
                - name: rabbitmq
                  persistentVolumeClaim:
                      claimName: rabbit-single
            hostname: rabbitmq-cp
            restartPolicy: Always
```
Then execute df -h in the container.
```
df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  10.0G      7.8G      2.2G  78% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     1.8G         0      1.8G   0% /sys/fs/cgroup
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/mapper/ol-var       10.0G      7.8G      2.2G  78% /etc/hosts
/dev/mapper/ol-var       10.0G      7.8G      2.2G  78% /dev/termination-log
/dev/mapper/ol-var       10.0G      7.8G      2.2G  78% /etc/hostname
/dev/mapper/ol-var       10.0G      7.8G      2.2G  78% /etc/resolv.conf
/dev/longhorn/pvc-a1e36f78-8c80-4feb-9c48-16bb72b0c32c
                        975.9M    319.2M    640.7M  33% /var/lib/rabbitmq
tmpfs                     1.8G     12.0K      1.8G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     1.8G         0      1.8G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     1.8G         0      1.8G   0% /proc/scsi
tmpfs                     1.8G         0      1.8G   0% /sys/firmware
```
Hmmm... 320Mb of /var/lib/rabbimq. Strange....
Let's look what we got there.
Almost 320Mb used by wal file
```
bash-5.1# du -sh /var/lib/rabbitmq/mnesia/rabbit\@rabbitmq-cp/quorum/rabbit\@rabbitmq-cp/* | sort
314.1M  /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-cp/quorum/rabbit@rabbitmq-cp/00000001.wal
8.0K    /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-cp/quorum/rabbit@rabbitmq-cp/meta.dets
8.0K    /var/lib/rabbitmq/mnesia/rabbit@rabbitmq-cp/quorum/rabbit@rabbitmq-cp/names.dets
```

So, my question is why this is this file so big with an empty configuration of rabbitmq? I mean that there is no queues and load on the server.
And there is another moment. 
When I use my PVC in **ReadWriteMany** mode the whole size of /var/lib/rabbitmq is about 4Mb. In this mode PV is mounted as nfs point in a container.
