### ISSUE TITLE
Recreate database after each docker restart

### ISSUE THREAD

**Issue by maffpool** [docker-library/rabbitmq#51]
I use docker-compose like this :

```yml
rabbitmq:
  image: rabbitmq:3-management
  ports:
    - 15672:15672
  env_file:
    - config/environment
  volumes_from:
    - data

data:
  build: docker/data
  volumes:
    - data/rabbitmq:/var/lib/rabbitmq
```

Unfortunately, after each docker-compose stop / rm / start, the new instance of the rabbitmq container recreates its database structure, instead of using the existing one

After 3 starts, my mnesia folder looks like this :

```
rabbit@3545369b0be7/
rabbit@3545369b0be7.pid
rabbit@3545369b0be7-plugins-expand/
rabbit@8d59c5c0918b/
rabbit@8d59c5c0918b.pid
rabbit@8d59c5c0918b-plugins-expand/
rabbit@dd9f4e63f2fa/
rabbit@dd9f4e63f2fa.pid
rabbit@dd9f4e63f2fa-plugins-expand/
```

Any idea / help would be appreciated :)

(my data container works well with other containers such as pg, nginx, etc)
