### ISSUE TITLE
TLS Fatal - Certificate Unknown

### ISSUE THREAD

**Issue by LukasHvizdak** [docker-library/rabbitmq#532]
Hi, 
I created certificates according to your example with python scripts.
However, I am no more able to connect to rabbitmq port 5672. My client is returning an error "Create connection error :  OperationalError: Socket closed abruptly during opening handshake."
And Rabbitmq is periodically showing an error "2021-11-29 15:16:01.141676+00:00 [noti] <0.852.0> TLS server: In state wait_finished received CLIENT ALERT: Fatal - Certificate Unknown". 

If I allow not SSL verification of client then everything working fine expect is not under SSL. 
### my docker -compose.yml
```yaml
version: "3.2"
services:
   rabbitmq:
    user: rabbitmq
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data/:/var/lib/rabbitmq/mnesia/
        - ./log/:/var/log/rabbitmq/
        - ./etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        - ./certs/:/home/certs/
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge`
```

### my rabbitmq config
```
listeners.ssl.default = 5672
default_pass = test
default_user = test
hipe_compile = false
management.listener.port = 15672
management.listener.ssl = true
log.file.level = info
ssl_options.cacertfile = /home/certs/ca_certificate.pem
ssl_options.certfile   = /home/certs/server_certificate.pem
ssl_options.keyfile    = /home/certs/server_key.pem
ssl_options.password             = test
ssl_options.verify               = verify_peer
ssl_options.fail_if_no_peer_cert = true
ssl_options.versions.1 = tlsv1.3
ssl_options.versions.2 = tlsv1.2
ssl_options.depth  = 2
listeners.tcp = none

ssl_options.ciphers.1  = TLS_AES_256_GCM_SHA384
ssl_options.ciphers.2  = TLS_AES_128_GCM_SHA256
ssl_options.ciphers.3  = TLS_CHACHA20_POLY1305_SHA256
ssl_options.ciphers.4  = TLS_AES_128_CCM_SHA256
ssl_options.ciphers.5  = TLS_AES_128_CCM_8_SHA256
```
