### ISSUE TITLE
3.9-management image missing rabbitmq-diagnostics

### ISSUE THREAD

**Issue by raszkiewicz** [docker-library/rabbitmq#538]
trying to run liveness probe as

```
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics -q ping
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 30

```

but getting

```
exec: "rabbitmq-diagnostics -q ping": executable file not found in $PATH: unknown
```

when it was working fine in the past.
