### ISSUE TITLE
Cannot set TimeZone

### ISSUE THREAD

**Issue by MrAliev** [docker-library/rabbitmq#557]
How can I set a time zone when running an image in docker? 
Setting the environment variable in "docker-compose.yml" file
```
rabbitmq:
    image: masstransit/rabbitmq
    environment:
      TZ: 'Europe/Berlin'
...
```
does not lead to the desired result
