### ISSUE TITLE
Environment variables cannot be read on ubuntu

### ISSUE THREAD

**Issue by jwrookie** [docker-library/rabbitmq#594]
```
rabbitmq:
    image: docker.io/rabbitmq:3.11.4-management
    container_name: rocketmq
    restart: always
    hostname: scan_tx_rabbitmq
    volumes:
      - ~/www/data/scan-tx/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "45672:5672"
      - "35672:15672" # rabbitmq management
    networks:
      - scan_tx
```

The above docker compose file does not work properly under ubuntu 20.04, he will use the default user guest

But it works fine on centos
