### ISSUE TITLE
Rabbitmqctl couldn't connect to local node

### ISSUE THREAD

**Issue by AlexPCRus** [docker-library/rabbitmq#598]
Hi!

I use docker-compose to setup rabbitmq service:
```
    rabbitmq1:
        image: rabbitmq:3-management
        hostname: rabbitmq1
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=rmuser
            - RABBITMQ_DEFAULT_PASS=rmpassword
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
            - RABBITMQ_ERLANG_COOKIE=SUPER1SECRET1COOKIE
            - RABBITMQ_NODENAME=master
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
        command: ["bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server"]
        networks:
            - myrabbitmq
```

When i run a container and /bin/bash into it, every use of rabbitmqctl returns an error:
"Unable to perform an operation on node master@rabbitmq1" even "rabbitmqctl status".

Why rabbitmqctl couldn't connect to local node in management image? Is there another CLI way to tune rabbitmq into container?
