### ISSUE TITLE
Permission denied when passing SSL certificates

### ISSUE THREAD

**Issue by mavdi** [docker-library/rabbitmq#66]
Running the container with the following settings:

```yml
rb:
  image: rabbitmq
  volumes:
    - ./certificates:/certificates
  environment:
    RABBITMQ_SSL_CERT_FILE: /certificates/server/cert.pem
    RABBITMQ_SSL_KEY_FILE:  /certificates/server/key.pem
    RABBITMQ_SSL_CA_FILE: /certificates/ca/cacert.pem
  ports:
    - "15672:15672"
    - "5672:5672"
    - "1883:1883"
```

getting:

```bash
/docker-entrypoint.sh: line 132: /tmp/combined.pem: Permission denied
```

The script doesn't have access to the temp combined file it creates?

Edit: After many tries it starts up sometimes, it seems to me some sort of race condition.
