### ISSUE TITLE
Error: unsupported type in amqp table: undefined

### ISSUE THREAD

**Issue by marinsicavirdol** [docker-library/rabbitmq#98]
Hello,

I have the following docker-compose file:

```
version: '2'
services:
  mongo:
    hostname: dev
    container_name: mongo
    image: mongo:3.2
    ports:
      - "27017:27017"
    networks:
      - node-network
  application:
    hostname: dev
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run watch
    environment: 
      LOG_LEVEL: info
      PORT: "5000"
      AMQP_HOST: rabbitmq-service
      AMQP_USER: root
      AMQP_PASSWORD: parola
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASSWORD: parola
      DB_NAME: test
    ports:
      - "5000:5000"
      - "5858:5858"
    volumes: 
      - ./:/app
    networks:
      - node-network
  rabbitmq-service:
    hostname: dev
    container_name: rabbitmq-service
    image: rabbitmq:3.6-management
    ports:
        - "15672:15672"
        - "5672:5672"
    environment: 
      RABBITMQ_DEFAULT_PASS: parola
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_HIPE_COMPILE: 1
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

```

And the following connection code to rabbitmq: (coffeescript)

```
connection  = amqp.createConnection(
	{
		host: "#{process.env.AMQP_HOST}"
		login: "#{process.env.AMQP_USER}"
		password: "#{process.env.AMQP_PASSWORD}"
		vhost: "#{process.env.AMQP_VHOST || '/'}"
		port: process.env.AMQP_PORT || 5672
		clientProperties:
			applicationName: process.env.SERVICE_NAME
	}
	{
		defaultExchangeName: "amq.topic"
		reconnect: true
		reconnectBackoffStrategy: 'exponential'
		reconnectExponentialLimit: 120000
		reconnectBackoffTime: 2000
	}
)
```

When running docker-compose up I'm keep getting the following error:
`Error: unsupported type in amqp table: undefined`

Running the same code without docker works just fine. Can anyone help me with this issue?
